server.port=8081
spring.application.name=task14

# TRYB
# app.auth.method=basic
app.auth.method=api-key

# BASIC
app.auth.basic.username=admin
app.auth.basic.password=secret

# API KEY
app.auth.api-key.header=X-API-KEY
app.auth.api-key.value=super-secret-api-key

spring.datasource.url=jdbc:hsqldb:mem:testdb
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
